import { DigitalDocument } from "..";
import { ImageQuality } from "../../../intangible/quantity/display";

export enum ImageDocumentFormat {
  ANI = 'ani',
  ANIM = 'anim',
  APNG = 'apng',
  ART = 'art',
  BMP = 'bmp',
  BPG = 'bpg',
  BSAVE = 'bsave',
  CAL = 'cal',
  CIN = 'cin',
  CPC = 'cpc',
  CPT = 'cpt',
  DDS = 'dds',
  DPX = 'dpx',
  ECW = 'ecw',
  EXR = 'exr',
  FITS = 'fits',
  FLIC = 'flic',
  FLIF = 'flif',
  FPX = 'fpx',
  GIF = 'gif',
  HDRI = 'hdri',
  HEVC = 'hevc',
  ICER = 'icer',
  ICNS = 'icns',
  ICO = 'ico',
  CUR = 'cur',
  ICS = 'ics',
  ILBM = 'ilbm',
  JBIG = 'jbig',
  JBIG2 = 'jbig2',
  JNG = 'jng',
  JPEG = 'jpeg',
  KRA = 'kra',
  MNG = 'mng',
  MIFF = 'miff',
  NRRD = 'nrrd',
  PAM = 'pam',
  PBM = 'pbm',
  PGM = 'pgm',
  PPM = 'ppm',
  PNM = 'pnm',
  PCX = 'pcx',
  PGF = 'pgf',
  PICTOR = 'pictor',
  PNG = 'png',
  PSD = 'psd',
  PSB = 'psb',
  PSP = 'psp',
  QTVR = 'qtvr',
  RAS = 'ras',
  RGBE = 'rgbe',
  IFF = 'iff',
  SGI = 'sgi',
  TGA = 'tga',
  UFO = 'ufo',
  UFP = 'ufp',
  WBMP = 'wbmp',
  WEBP = 'webp',
  XBM = 'xbm',
  XCF = 'xcf',
  XPM = 'xpm',
  XWD = 'xwd',
  CIFF = 'ciff',
  DNG = 'dng',
  AI = 'ai',
  CDR = 'cdr',
  CGM = 'cgm',
  DXF = 'dxf',
  EVA = 'eva',
  EMF = 'emf',
  GERBER = 'gerber',
  HVIF = 'hvif',
  IGES = 'iges',
  PGML = 'pgml',
  SVG = 'svg',
  VML = 'vml',
  WMF = 'wmf',
  XAR = 'xar',
  CDF = 'cdf',
  DJVU = 'djvu',
  EPS = 'eps',
  PDF = 'pdf',
  PICT = 'pict',
  PS = 'ps',
  SWF = 'swf',
  XAML = 'xaml',
  RAW = 'raw',
}

export const IMAGE_DOCUMENT_FORMATS = { ...ImageDocumentFormat };

export interface ImageDocument extends DigitalDocument {
  format: ImageDocumentFormat;
  imageQuality?: ImageQuality;
}
